apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtpengine
  namespace: voip-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtpengine
  template:
    metadata:
      labels:
        app: rtpengine
    spec:
      hostNetwork: true
      containers:
        - name: rtpengine
          image: myrtp-custom:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              echo "Starting RTPengine with interface eth0..."
              # Keep RTPengine running continuously
              while true; do
                /usr/local/bin/rtpengine \
                  --interface=eth0 \
                  --listen-ng=0.0.0.0:22222 \
                  --listen-udp=0.0.0.0:2223 \
                  --port-min=16384 \
                  --port-max=16484 \
                  --foreground \
                  --log-level=7 \
                  --tos=184 \
                  --silent-timeout=3600 \
                  --final-timeout=3600
                echo "RTPengine exited with code $?. Restarting in 2 seconds..."
                sleep 2
              done
          ports:
            - containerPort: 22222
              protocol: UDP
            - containerPort: 2223
              protocol: UDP
            - containerPort: 16384
              protocol: UDP
            - containerPort: 16484
              protocol: UDP
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command: ["sh", "-c", "ss -uln | grep -q ':22222'"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "ss -uln | grep -q ':22222'"]
            initialDelaySeconds: 25
            periodSeconds: 15
            timeoutSeconds: 5
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "SYS_NICE"]
            runAsNonRoot: false
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: rtpengine
  namespace: voip-test2
spec:
  selector:
    app: rtpengine
  ports:
    - name: ng-control
      port: 22222
      targetPort: 22222
      protocol: UDP