# freeswitch-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeswitch-config
  namespace: voip-test2
data:
  # SIP Profile - NO AUTHENTICATION
  sip_profiles_internal.xml: |
    <include>
      <profile name="internal">
        <param name="ext-rtp-ip" value="$${local_ip_v4}"/>
        <param name="ext-sip-ip" value="$${local_ip_v4}"/>
        <param name="sip-port" value="5060"/>
        <param name="rtp-ip" value="$${local_ip_v4}"/>
        <param name="rtp-engine" value="rtpengine"/>
        <param name="dialplan" value="XML"/>
        <param name="context" value="default"/>
        <param name="apply-nat-acl" value="rfc1918.auto"/>
        <param name="apply-inbound-acl" value="any"/>
        <!-- DISABLE AUTHENTICATION -->
        <param name="accept-blind-auth" value="true"/>
        <param name="accept-blind-reg" value="true"/>
        <param name="auth-calls" value="false"/>
        <param name="inbound-reg-force-matching-username" value="false"/>
      </profile>
    </include>

  # Dialplan - Simple echo test for any caller
  dialplan_default.xml: |
    <include>
      <context name="default">
        <extension name="no_auth_echo">
          <condition field="destination_number" expression="^(1000|9196)$">
            <action application="answer"/>
            <action application="set" data="rtp_use_rtpengine=true"/>
            <action application="set" data="rtpengine_args=replace-origin replace-session-connection"/>
            <action application="echo"/>
          </condition>
        </extension>
        
        <extension name="catch_all">
          <condition field="destination_number" expression="^.*$">
            <action application="answer"/>
            <action application="set" data="rtp_use_rtpengine=true"/>
            <action application="playback" data="ivr/ivr-welcome_to_freeswitch.wav"/>
            <action application="sleep" data="1000"/>
            <action application="say" data="en number pronounced 1234"/>
            <action application="hangup"/>
          </condition>
        </extension>
      </context>
    </include>

  # Keep other configs the same...
  autoload_configs_modules.conf.xml: |
    <configuration name="modules.conf" description="Modules">
      <modules>
        <load module="mod_rtpengine"/>
        <load module="mod_sofia"/>
        <load module="mod_loopback"/>
        <load module="mod_commands"/>
        <load module="mod_conference"/>
        <load module="mod_dialplan_xml"/>
        <load module="mod_dptools"/>
        <load module="mod_event_socket"/>
        <load module="mod_hash"/>
        <load module="mod_voicemail"/>
        <load module="mod_logfile"/>
      </modules>
    </configuration>

  autoload_configs_rtp.conf.xml: |
    <configuration name="rtp.conf" description="RTP Configuration">
      <settings>
        <param name="rtp-engine" value="rtpengine"/>
        <param name="rtpengine-ng-control" value="rtpengine:22222"/>
        <param name="rtp-start-port" value="16384"/>
        <param name="rtp-end-port" value="16484"/>
        <param name="rtp-timer-name" value="soft"/>
      </settings>
    </configuration>

  autoload_configs_rtpengine.conf.xml: |
    <configuration name="rtpengine.conf" description="RTPEngine Configuration">
      <settings>
        <param name="ng-control" value="rtpengine:22222"/>
        <param name="enable" value="true"/>
        <param name="log-level" value="7"/>
      </settings>
    </configuration>

  vars.xml: |
    <include>
      <X-PRE-PROCESS cmd="set" data="domain=$${local_ip_v4}"/>
      <X-PRE-PROCESS cmd="set" data="rtp_ng_control=rtpengine:22222"/>
      <X-PRE-PROCESS cmd="set" data="internal_sip_port=5060"/>
      <X-PRE-PROCESS cmd="set" data="rtp_start_port=16384"/>
      <X-PRE-PROCESS cmd="set" data="rtp_end_port=16484"/>
      <X-PRE-PROCESS cmd="set" data="local_ip_v4=$${local_ip_v4}"/>
    </include>