# freeswitch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch
  namespace: voip-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      containers:
        - name: freeswitch
          image: custom-fsrtp:latest
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/freeswitch/bin/freeswitch"]
          args: ["-nonat", "-nf"]
          ports:
            - containerPort: 5060
              protocol: UDP
            - containerPort: 16384
              protocol: UDP
            - containerPort: 16484
              protocol: UDP
          volumeMounts:
            - name: freeswitch-config
              mountPath: /etc/freeswitch/sip_profiles/internal.xml
              subPath: sip_profiles_internal.xml
            - name: freeswitch-config
              mountPath: /etc/freeswitch/autoload_configs/modules.conf.xml
              subPath: autoload_configs_modules.conf.xml
            - name: freeswitch-config
              mountPath: /etc/freeswitch/autoload_configs/rtp.conf.xml
              subPath: autoload_configs_rtp.conf.xml
            - name: freeswitch-config
              mountPath: /etc/freeswitch/autoload_configs/rtpengine.conf.xml
              subPath: autoload_configs_rtpengine.conf.xml
            - name: freeswitch-config
              mountPath: /etc/freeswitch/vars.xml
              subPath: vars.xml
            - name: freeswitch-config
              mountPath: /etc/freeswitch/dialplan/default.xml
              subPath: dialplan_default.xml
          livenessProbe:
            exec:
              command: ["/usr/local/freeswitch/bin/fs_cli", "-x", "status"]
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["/usr/local/freeswitch/bin/fs_cli", "-x", "status"]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: freeswitch-config
          configMap:
            name: freeswitch-config
            defaultMode: 0644

---
apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  namespace: voip-test2
spec:
  type: NodePort
  selector:
    app: freeswitch
  ports:
    - name: sip
      port: 5060
      protocol: UDP
      nodePort: 30060
    - name: rtp-start
      port: 16384
      protocol: UDP
      nodePort: 31684
    - name: rtp-end
      port: 16484
      protocol: UDP
      nodePort: 31685